# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e31ad297e195d1d9ef6c73c00928be9d7f31d91f5853ba178b69a9231e40b2461837384391869fc4a7367e6b5f3cc40df42abeb190ed33e1daecbbb08b8c11c4

test:
  secret_key_base: 67af34cc006ab05d75730aceb905f2a49de3262e1e984b1d6ec18c2323fce5a52a6ac0ac605c0db7e04ff74ea0fcea6df1faba79caa4b443e710175a56b621fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
